<Project Sdk="Microsoft.NET.Sdk">

  <Sdk Name="Aspire.AppHost.Sdk" Version="9.3.1" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<AspireUseCliBundle>true</AspireUseCliBundle>
    <UserSecretsId>a16de04c-26aa-422a-8c66-04e21fc49c58</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="13.5.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hybrsoft.FoundationAPI\Hybrsoft.FoundationAPI.csproj" />
  </ItemGroup>

</Project>
