<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>c5d034c5-7010-4a69-8ba3-ebb5a33b27e7</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hybrsoft.AspireServiceDefaults\Hybrsoft.AspireServiceDefaults.csproj" />
    <ProjectReference Include="..\Hybrsoft.Domain\Hybrsoft.Domain.csproj" />
    <ProjectReference Include="..\Hybrsoft.DTOs\Hybrsoft.DTOs.csproj" />
    <ProjectReference Include="..\Hybrsoft.Infrastructure\Hybrsoft.Infrastructure.csproj" />
  </ItemGroup>

</Project>
